on:
  workflow_dispatch:
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: kulakmateuszorganization/GitHub_Actions_secrets/GitHub_Actions_secrets/my-composite-action@main #⬅ Zmienić 
        with:
          who-to-greet: Mateusz #⬅ Uwaga
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}
