name: dispatch
on:
  workflow_dispatch:
    inputs:
      logLevel:
        required: true
        default: 'warning'
        type: choice
        options:
          - 'warning'
          - 'info'
          - 'debug'
      environment:
        type: environment
      tags:
        required: false
        type: string

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Log the inputs
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"
          echo "Environment: $ENVIRONMENT"
        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}